# Generated by Django 3.0.4 on 2020-03-15 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('phone_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('price', models.FloatField(max_length=60)),
                ('volume', models.IntegerField()),
                ('alcohol', models.BooleanField()),
                ('custom', models.BooleanField()),
                ('time', models.IntegerField()),
                ('cafe', models.ManyToManyField(to='myapi.Cafe')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('quantity_mu', models.CharField(max_length=20)),
                ('price_per_unit', models.FloatField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(max_length=60)),
                ('date', models.DateField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='OrderCocktail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_of_cocktails', models.IntegerField()),
                ('cocktail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.Cocktail')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='CocktailIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cocktail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.Cocktail')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='CafeIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.Cocktail')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.Ingredient')),
            ],
        ),
    ]
