# Generated by Django 3.0.4 on 2020-03-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_of_cocktails',
            field=models.ManyToManyField(to='myapi.Cocktail'),
        ),
        migrations.DeleteModel(
            name='OrderCocktail',
        ),
    ]
