# Generated by Django 3.0.4 on 2020-03-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20200317_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='time',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='volume',
            field=models.FloatField(),
        ),
    ]
