# Generated by Django 3.0.4 on 2020-04-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_auto_20200421_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionaluserinfo',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
    ]
