# Generated by Django 3.0.4 on 2020-04-22 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_additionaluserinfo_dark_mode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdditionalUserInfo',
        ),
    ]
