# Generated by Django 3.0.4 on 2020-06-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_delete_additionaluserinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='img',
            field=models.CharField(default='images/logo.png', max_length=60),
            preserve_default=False,
        ),
    ]
